#:schema https://cdn.jsdelivr.net/gh/crate-ci/typos@master/config.schema.json

[default]
locale = "en"

[files]
extend-exclude = [
  "LICENSES",
  "src/legacy-extension/_locales/*",
  "src/legacy-extension/common/highlightjs",
  "src/legacy-extension/common/marked.js",
  "src/legacy-extension/common/vendor/dompurify.min.js",
]

[default.extend-identifiers]
curren = "curren"
